//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPG.SoftwareFactory.Service.LoggerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoggerServiceRef.ILogger")]
    public interface ILogger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoFormatThreeArgs", ReplyAction="http://tempuri.org/ILogger/InfoFormatThreeArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoFormatThreeArgs(string format, object arg0, object arg1, object arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnMessage", ReplyAction="http://tempuri.org/ILogger/WarnMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnMessage(object message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnMessageException", ReplyAction="http://tempuri.org/ILogger/WarnMessageExceptionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnMessageException(object message, System.Exception exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnFormatArg", ReplyAction="http://tempuri.org/ILogger/WarnFormatArgResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnFormatArg(string format, object arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnFormatParams", ReplyAction="http://tempuri.org/ILogger/WarnFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnFormatParams(string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnProviderFormatParams", ReplyAction="http://tempuri.org/ILogger/WarnProviderFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnProviderFormatParams(object provider, string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnFormatTwoArgs", ReplyAction="http://tempuri.org/ILogger/WarnFormatTwoArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnFormatTwoArgs(string format, object arg0, object arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/WarnFormatThreeArgs", ReplyAction="http://tempuri.org/ILogger/WarnFormatThreeArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void WarnFormatThreeArgs(string format, object arg0, object arg1, object arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/TestMessage", ReplyAction="http://tempuri.org/ILogger/TestMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void TestMessage(TPG.SoftwareFactory.Contract.ObjectContainer message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugMessage", ReplyAction="http://tempuri.org/ILogger/DebugMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugMessage(object message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugMessageException", ReplyAction="http://tempuri.org/ILogger/DebugMessageExceptionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugMessageException(object message, System.Exception exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugFormatArg", ReplyAction="http://tempuri.org/ILogger/DebugFormatArgResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugFormatArg(string format, object arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugFormatParams", ReplyAction="http://tempuri.org/ILogger/DebugFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugFormatParams(string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugProviderFormatParams", ReplyAction="http://tempuri.org/ILogger/DebugProviderFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugProviderFormatParams(object provider, string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugFormatTwoArgs", ReplyAction="http://tempuri.org/ILogger/DebugFormatTwoArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugFormatTwoArgs(string format, object arg0, object arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/DebugFormatThreeArgs", ReplyAction="http://tempuri.org/ILogger/DebugFormatThreeArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void DebugFormatThreeArgs(string format, object arg0, object arg1, object arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorMessage", ReplyAction="http://tempuri.org/ILogger/ErrorMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorMessage(object message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorMessageException", ReplyAction="http://tempuri.org/ILogger/ErrorMessageExceptionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorMessageException(object message, System.Exception exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorFormatArg", ReplyAction="http://tempuri.org/ILogger/ErrorFormatArgResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorFormatArg(string format, object arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorFormatParams", ReplyAction="http://tempuri.org/ILogger/ErrorFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorFormatParams(string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorProviderFormatParams", ReplyAction="http://tempuri.org/ILogger/ErrorProviderFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorProviderFormatParams(object provider, string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorFormatTwoArgs", ReplyAction="http://tempuri.org/ILogger/ErrorFormatTwoArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorFormatTwoArgs(string format, object arg0, object arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/ErrorFormatThreeArgs", ReplyAction="http://tempuri.org/ILogger/ErrorFormatThreeArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void ErrorFormatThreeArgs(string format, object arg0, object arg1, object arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalMessage", ReplyAction="http://tempuri.org/ILogger/FatalMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalMessage(object message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalMessageException", ReplyAction="http://tempuri.org/ILogger/FatalMessageExceptionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalMessageException(object message, System.Exception exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalFormatArg", ReplyAction="http://tempuri.org/ILogger/FatalFormatArgResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalFormatArg(string format, object arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalFormatParams", ReplyAction="http://tempuri.org/ILogger/FatalFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalFormatParams(string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalProviderFormatParams", ReplyAction="http://tempuri.org/ILogger/FatalProviderFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalProviderFormatParams(object provider, string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalFormatTwoArgs", ReplyAction="http://tempuri.org/ILogger/FatalFormatTwoArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalFormatTwoArgs(string format, object arg0, object arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/FatalFormatThreeArgs", ReplyAction="http://tempuri.org/ILogger/FatalFormatThreeArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void FatalFormatThreeArgs(string format, object arg0, object arg1, object arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoMessage", ReplyAction="http://tempuri.org/ILogger/InfoMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoMessage(object message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoMessageException", ReplyAction="http://tempuri.org/ILogger/InfoMessageExceptionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoMessageException(object message, System.Exception exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoFormatArg", ReplyAction="http://tempuri.org/ILogger/InfoFormatArgResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoFormatArg(string format, object arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoFormatParams", ReplyAction="http://tempuri.org/ILogger/InfoFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoFormatParams(string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoProviderFormatParams", ReplyAction="http://tempuri.org/ILogger/InfoProviderFormatParamsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoProviderFormatParams(object provider, string format, object[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogger/InfoFormatTwoArgs", ReplyAction="http://tempuri.org/ILogger/InfoFormatTwoArgsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TPG.SoftwareFactory.Contract.ObjectContainer))]
        void InfoFormatTwoArgs(string format, object arg0, object arg1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoggerChannel : TPG.SoftwareFactory.Service.LoggerServiceRef.ILogger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggerClient : System.ServiceModel.ClientBase<TPG.SoftwareFactory.Service.LoggerServiceRef.ILogger>, TPG.SoftwareFactory.Service.LoggerServiceRef.ILogger {
        
        public LoggerClient() {
        }
        
        public LoggerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InfoFormatThreeArgs(string format, object arg0, object arg1, object arg2) {
            base.Channel.InfoFormatThreeArgs(format, arg0, arg1, arg2);
        }
        
        public void WarnMessage(object message) {
            base.Channel.WarnMessage(message);
        }
        
        public void WarnMessageException(object message, System.Exception exception) {
            base.Channel.WarnMessageException(message, exception);
        }
        
        public void WarnFormatArg(string format, object arg0) {
            base.Channel.WarnFormatArg(format, arg0);
        }
        
        public void WarnFormatParams(string format, object[] args) {
            base.Channel.WarnFormatParams(format, args);
        }
        
        public void WarnProviderFormatParams(object provider, string format, object[] args) {
            base.Channel.WarnProviderFormatParams(provider, format, args);
        }
        
        public void WarnFormatTwoArgs(string format, object arg0, object arg1) {
            base.Channel.WarnFormatTwoArgs(format, arg0, arg1);
        }
        
        public void WarnFormatThreeArgs(string format, object arg0, object arg1, object arg2) {
            base.Channel.WarnFormatThreeArgs(format, arg0, arg1, arg2);
        }
        
        public void TestMessage(TPG.SoftwareFactory.Contract.ObjectContainer message) {
            base.Channel.TestMessage(message);
        }
        
        public void DebugMessage(object message) {
            base.Channel.DebugMessage(message);
        }
        
        public void DebugMessageException(object message, System.Exception exception) {
            base.Channel.DebugMessageException(message, exception);
        }
        
        public void DebugFormatArg(string format, object arg0) {
            base.Channel.DebugFormatArg(format, arg0);
        }
        
        public void DebugFormatParams(string format, object[] args) {
            base.Channel.DebugFormatParams(format, args);
        }
        
        public void DebugProviderFormatParams(object provider, string format, object[] args) {
            base.Channel.DebugProviderFormatParams(provider, format, args);
        }
        
        public void DebugFormatTwoArgs(string format, object arg0, object arg1) {
            base.Channel.DebugFormatTwoArgs(format, arg0, arg1);
        }
        
        public void DebugFormatThreeArgs(string format, object arg0, object arg1, object arg2) {
            base.Channel.DebugFormatThreeArgs(format, arg0, arg1, arg2);
        }
        
        public void ErrorMessage(object message) {
            base.Channel.ErrorMessage(message);
        }
        
        public void ErrorMessageException(object message, System.Exception exception) {
            base.Channel.ErrorMessageException(message, exception);
        }
        
        public void ErrorFormatArg(string format, object arg0) {
            base.Channel.ErrorFormatArg(format, arg0);
        }
        
        public void ErrorFormatParams(string format, object[] args) {
            base.Channel.ErrorFormatParams(format, args);
        }
        
        public void ErrorProviderFormatParams(object provider, string format, object[] args) {
            base.Channel.ErrorProviderFormatParams(provider, format, args);
        }
        
        public void ErrorFormatTwoArgs(string format, object arg0, object arg1) {
            base.Channel.ErrorFormatTwoArgs(format, arg0, arg1);
        }
        
        public void ErrorFormatThreeArgs(string format, object arg0, object arg1, object arg2) {
            base.Channel.ErrorFormatThreeArgs(format, arg0, arg1, arg2);
        }
        
        public void FatalMessage(object message) {
            base.Channel.FatalMessage(message);
        }
        
        public void FatalMessageException(object message, System.Exception exception) {
            base.Channel.FatalMessageException(message, exception);
        }
        
        public void FatalFormatArg(string format, object arg0) {
            base.Channel.FatalFormatArg(format, arg0);
        }
        
        public void FatalFormatParams(string format, object[] args) {
            base.Channel.FatalFormatParams(format, args);
        }
        
        public void FatalProviderFormatParams(object provider, string format, object[] args) {
            base.Channel.FatalProviderFormatParams(provider, format, args);
        }
        
        public void FatalFormatTwoArgs(string format, object arg0, object arg1) {
            base.Channel.FatalFormatTwoArgs(format, arg0, arg1);
        }
        
        public void FatalFormatThreeArgs(string format, object arg0, object arg1, object arg2) {
            base.Channel.FatalFormatThreeArgs(format, arg0, arg1, arg2);
        }
        
        public void InfoMessage(object message) {
            base.Channel.InfoMessage(message);
        }
        
        public void InfoMessageException(object message, System.Exception exception) {
            base.Channel.InfoMessageException(message, exception);
        }
        
        public void InfoFormatArg(string format, object arg0) {
            base.Channel.InfoFormatArg(format, arg0);
        }
        
        public void InfoFormatParams(string format, object[] args) {
            base.Channel.InfoFormatParams(format, args);
        }
        
        public void InfoProviderFormatParams(object provider, string format, object[] args) {
            base.Channel.InfoProviderFormatParams(provider, format, args);
        }
        
        public void InfoFormatTwoArgs(string format, object arg0, object arg1) {
            base.Channel.InfoFormatTwoArgs(format, arg0, arg1);
        }
    }
}
